permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""

title: "Wuping"
email: "1562941990@qq.com"
description: "A iOS Coder"
github_username:  "acewu1205"
swiftype_searchId: "xx"
disqus_shortname: "xxxx"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js, toc.js]



url: "https://acewu1205.github.io"
imgrepo: "https://acewu1205.github.io/static/img"

# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"


theme: jekyll-theme-time-machine